### ISSUE TITLE
Dataset for training

### ISSUE THREAD

**Issue by dfayzur** [IlliaOvcharenko/lung-segmentation#5]
Thanks for sharing the great repo. May I ask what dataset you used to train the segmentation?

**Comment by IlliaOvcharenko** [comment]
Sorry for such a huge delay with the response, I have been just noticed that there is an opened issue. In case it is still actual for you here it is https://drive.google.com/file/d/1ffbbyoPf-I3Y0iGbBahXpWqYdGd7xxQQ/view
